Got build scripts doing the right thing on 10.2.

diff --git a/Scripts/BuildMIDIMonitor b/Scripts/BuildMIDIMonitor
--- a/Scripts/BuildMIDIMonitor
+++ b/Scripts/BuildMIDIMonitor
@@ -2,6 +2,9 @@
 #
 # Script to build the release version of the MIDI Monitor application.
 
+# Display commands as they happen -- useful for debugging
+# setopt XTRACE
+
 ThisScriptDir=`dirname ${PWD}/$0`
 
 SourceRoot=~/Source
@@ -64,22 +67,22 @@ fi
 if [[ $DO_CLEAN -eq 1 ]] ; then
 
 	cd ${OmniFrameworkSource}/OmniBase
-	pbxbuild -buildstyle $FRAMEWORK_BUILDSTYLE clean || (echo "Build failed!"; exit 1)
+	pbxbuild -buildstyle $FRAMEWORK_BUILDSTYLE clean || {echo "Build failed!"; exit 1}
 
 	cd ${OmniFrameworkSource}/OmniFoundation
 	pbxbuild -target "OmniFoundation (MIDIMonitor subset framework)" -buildstyle $FRAMEWORK_BUILDSTYLE clean || (echo "Build failed!"; exit 1)
 
 	cd ${SnoizeFrameworkSource}/SnoizeMIDI
-	pbxbuild -buildstyle $FRAMEWORK_BUILDSTYLE clean || (echo "Build failed!"; exit 1)
+	pbxbuild -buildstyle $FRAMEWORK_BUILDSTYLE clean || {echo "Build failed!"; exit 1}
 
 	cd ${SnoizeFrameworkSource}/SnoizeMIDISpy
-	pbxbuild -buildstyle $FRAMEWORK_BUILDSTYLE clean || (echo "Build failed!"; exit 1)
+	pbxbuild -buildstyle $FRAMEWORK_BUILDSTYLE clean || {echo "Build failed!"; exit 1}
 
 	cd ${SnoizeFrameworkSource}/DisclosableView
-	pbxbuild -buildstyle $FRAMEWORK_BUILDSTYLE clean || (echo "Build failed!"; exit 1)
+	pbxbuild -buildstyle $FRAMEWORK_BUILDSTYLE clean || {echo "Build failed!"; exit 1}
 
 	cd ${SnoizeAppSource}/MIDIMonitor
-	pbxbuild -buildstyle $APP_BUILDSTYLE clean || (echo "Build failed!"; exit 1)
+	pbxbuild -buildstyle $APP_BUILDSTYLE clean || {echo "Build failed!"; exit 1}
 
 fi
 
@@ -88,27 +91,27 @@ fi
 #
 
 if [[ $DO_INSTALL -eq 1 ]] ; then
-	mkdir -p "$INSTALL_DIRECTORY"
-	rm -rf "$INSTALL_DIRECTORY/$APP_WRAPPER_NAME"
+	mkdir -p "$INSTALL_DIRECTORY" || {echo "Couldn't cd to install directory!"; exit 1}
+	rm -rf "$INSTALL_DIRECTORY/$APP_WRAPPER_NAME" || {echo "Couldn't remove old installed app!"; exit 1}
 fi
 
 cd ${OmniFrameworkSource}/OmniBase
-pbxbuild -buildstyle $FRAMEWORK_BUILDSTYLE $BUILD_ACTION || (echo "Build failed!"; exit 1)
+pbxbuild -buildstyle $FRAMEWORK_BUILDSTYLE INSTALL_MODE_FLAG=go-w,a+rX $BUILD_ACTION || {echo "Build failed!"; exit 1}
 
 cd ${OmniFrameworkSource}/OmniFoundation
-pbxbuild -target "OmniFoundation (MIDIMonitor subset framework)" -buildstyle $FRAMEWORK_BUILDSTYLE $BUILD_ACTION || (echo "Build failed!"; exit 1)
+pbxbuild -target "OmniFoundation (MIDIMonitor subset framework)" -buildstyle $FRAMEWORK_BUILDSTYLE INSTALL_MODE_FLAG=go-w,a+rX $BUILD_ACTION || (echo "Build failed!"; exit 1)
 
 cd ${SnoizeFrameworkSource}/SnoizeMIDI
-pbxbuild -buildstyle $FRAMEWORK_BUILDSTYLE $BUILD_ACTION || (echo "Build failed!"; exit 1)
+pbxbuild -buildstyle $FRAMEWORK_BUILDSTYLE INSTALL_MODE_FLAG=go-w,a+rX $BUILD_ACTION || {echo "Build failed!"; exit 1}
 
 cd ${SnoizeFrameworkSource}/SnoizeMIDISpy
-pbxbuild -buildstyle $FRAMEWORK_BUILDSTYLE $BUILD_ACTION || (echo "Build failed!"; exit 1)
+pbxbuild -buildstyle $FRAMEWORK_BUILDSTYLE INSTALL_MODE_FLAG=go-w,a+rX $BUILD_ACTION || {echo "Build failed!"; exit 1}
 
 cd ${SnoizeFrameworkSource}/DisclosableView
-pbxbuild -buildstyle $FRAMEWORK_BUILDSTYLE $BUILD_ACTION || (echo "Build failed!"; exit 1)
+pbxbuild -buildstyle $FRAMEWORK_BUILDSTYLE INSTALL_MODE_FLAG=go-w,a+rX $BUILD_ACTION || {echo "Build failed!"; exit 1}
 
 cd ${SnoizeAppSource}/MIDIMonitor
-pbxbuild -buildstyle $APP_BUILDSTYLE DSTROOT= INSTALL_MODE_FLAG=go-w,a+rX $BUILD_ACTION || (echo "Build failed!"; exit 1)
+pbxbuild -buildstyle $APP_BUILDSTYLE DSTROOT=/ INSTALL_MODE_FLAG=go-w,a+rX $BUILD_ACTION || {echo "Build failed!"; exit 1}
 	# NOTE: We are relying on the app's project having an INSTALL_PATH
 	# set to $INSTALL_DIRECTORY. For some reason, if it is set to nothing in the project,
 	# setting it here will not cause the install to happen.
@@ -122,7 +125,7 @@ pbxbuild -buildstyle $APP_BUILDSTYLE DSTROOT= INSTALL_MODE_FLAG=go-w,a+rX $BUILD
 #
 
 if [[ $DO_INSTALL -eq 1 ]]; then
-	cd "$INSTALL_DIRECTORY/$APP_WRAPPER_NAME"
+	cd "$INSTALL_DIRECTORY/$APP_WRAPPER_NAME" || {echo "Couldn't cd to installed app!"; exit 1}
 	# Nobody needs the headers
 	find . -name 'Headers' -exec rm -rf {} \; -prune
 	# We don't need non-English localizations right now
@@ -135,13 +138,13 @@ fi
 #
 
 if [[ $DO_INSTALL -eq 1 ]]; then
-	cd "$INSTALL_DIRECTORY/$APP_WRAPPER_NAME/Contents/MacOS"
-	redo_prebinding -e "$PWD" ../Frameworks/OmniBase.framework/Versions/Current/OmniBase
-	redo_prebinding -e "$PWD" ../Frameworks/OmniFoundation.framework/Versions/Current/OmniFoundation
-	redo_prebinding -e "$PWD" ../Frameworks/SnoizeMIDI.framework/Versions/Current/SnoizeMIDI
-	redo_prebinding -e "$PWD" ../Frameworks/SnoizeMIDISpy.framework/Versions/Current/SnoizeMIDISpy
-	redo_prebinding -e "$PWD" ../Frameworks/DisclosableView.framework/Versions/Current/DisclosableView
-	redo_prebinding -e "$PWD" "./$APP_EXECUTABLE_NAME"
+	cd "$INSTALL_DIRECTORY/$APP_WRAPPER_NAME/Contents/MacOS" || {echo "Couldn't cd into installed app's Contents/MacOS!"; exit 1}
+	redo_prebinding -e "$PWD" ../Frameworks/OmniBase.framework/Versions/Current/OmniBase || exit 1
+	redo_prebinding -e "$PWD" ../Frameworks/OmniFoundation.framework/Versions/Current/OmniFoundation || exit 1
+	redo_prebinding -e "$PWD" ../Frameworks/SnoizeMIDI.framework/Versions/Current/SnoizeMIDI || exit 1
+	redo_prebinding -e "$PWD" ../Frameworks/SnoizeMIDISpy.framework/Versions/Current/SnoizeMIDISpy || exit 1
+	redo_prebinding -e "$PWD" ../Frameworks/DisclosableView.framework/Versions/Current/DisclosableView || exit 1
+	redo_prebinding -e "$PWD" "./$APP_EXECUTABLE_NAME" || exit 1
 fi
 
 #
