Updated scripts to add SnoizeMIDISpy.framework.

diff --git a/Scripts/BuildMIDIMonitor b/Scripts/BuildMIDIMonitor
--- a/Scripts/BuildMIDIMonitor
+++ b/Scripts/BuildMIDIMonitor
@@ -72,6 +72,9 @@ if [[ $DO_CLEAN -eq 1 ]] ; then
 	cd ${SnoizeFrameworkSource}/SnoizeMIDI
 	pbxbuild -buildstyle $FRAMEWORK_BUILDSTYLE clean || (echo "Build failed!"; exit 1)
 
+	cd ${SnoizeFrameworkSource}/SnoizeMIDISpy
+	pbxbuild -buildstyle $FRAMEWORK_BUILDSTYLE clean || (echo "Build failed!"; exit 1)
+
 	cd ${SnoizeAppSource}/MIDIMonitor
 	pbxbuild -buildstyle $APP_BUILDSTYLE clean || (echo "Build failed!"; exit 1)
 
@@ -93,6 +96,9 @@ cd ${OmniFrameworkSource}/OmniFoundation
 pbxbuild -target "OmniFoundation (MIDIMonitor subset framework)" -buildstyle $FRAMEWORK_BUILDSTYLE $BUILD_ACTION || (echo "Build failed!"; exit 1)
 
 cd ${SnoizeFrameworkSource}/SnoizeMIDI
+pbxbuild -buildstyle $FRAMEWORK_BUILDSTYLE $BUILD_ACTION || (echo "Build failed!"; exit 1)
+
+cd ${SnoizeFrameworkSource}/SnoizeMIDISpy
 pbxbuild -buildstyle $FRAMEWORK_BUILDSTYLE $BUILD_ACTION || (echo "Build failed!"; exit 1)
 
 cd ${SnoizeAppSource}/MIDIMonitor
@@ -127,6 +133,7 @@ if [[ $DO_INSTALL -eq 1 ]]; then
 	redo_prebinding -e "$PWD" ../Frameworks/OmniBase.framework/Versions/Current/OmniBase
 	redo_prebinding -e "$PWD" ../Frameworks/OmniFoundation.framework/Versions/Current/OmniFoundation
 	redo_prebinding -e "$PWD" ../Frameworks/SnoizeMIDI.framework/Versions/Current/SnoizeMIDI
+	redo_prebinding -e "$PWD" ../Frameworks/SnoizeMIDISpy.framework/Versions/Current/SnoizeMIDISpy
 	redo_prebinding -e "$PWD" "./$APP_EXECUTABLE_NAME"
 fi
 
