Use xcodebuild instead of pbxbuild.

diff --git a/Scripts/BuildMIDIMonitor b/Scripts/BuildMIDIMonitor
--- a/Scripts/BuildMIDIMonitor
+++ b/Scripts/BuildMIDIMonitor
@@ -69,16 +69,16 @@ fi
 if [[ $DO_CLEAN -eq 1 ]] ; then
 
 	cd ${SnoizeFrameworkSource}/SnoizeMIDI
-	pbxbuild -buildstyle $FRAMEWORK_BUILDSTYLE clean $EXTRA_SETTINGS || {echo "Build failed!"; exit 1}
+	xcodebuild -buildstyle $FRAMEWORK_BUILDSTYLE clean $EXTRA_SETTINGS || {echo "Build failed!"; exit 1}
 
 	cd ${SnoizeFrameworkSource}/SnoizeMIDISpy
-	pbxbuild -buildstyle $FRAMEWORK_BUILDSTYLE clean $EXTRA_SETTINGS || {echo "Build failed!"; exit 1}
+	xcodebuild -buildstyle $FRAMEWORK_BUILDSTYLE clean $EXTRA_SETTINGS || {echo "Build failed!"; exit 1}
 
 	cd ${SnoizeFrameworkSource}/DisclosableView
-	pbxbuild -buildstyle $FRAMEWORK_BUILDSTYLE clean $EXTRA_SETTINGS || {echo "Build failed!"; exit 1}
+	xcodebuild -buildstyle $FRAMEWORK_BUILDSTYLE clean $EXTRA_SETTINGS || {echo "Build failed!"; exit 1}
 
 	cd ${SnoizeAppSource}/MIDIMonitor
-	pbxbuild -buildstyle $APP_BUILDSTYLE clean $EXTRA_SETTINGS || {echo "Build failed!"; exit 1}
+	xcodebuild -buildstyle $APP_BUILDSTYLE clean $EXTRA_SETTINGS || {echo "Build failed!"; exit 1}
 
 fi
 
@@ -92,16 +92,16 @@ if [[ $DO_INSTALL -eq 1 ]] ; then
 fi
 
 cd ${SnoizeFrameworkSource}/SnoizeMIDI
-pbxbuild -buildstyle $FRAMEWORK_BUILDSTYLE INSTALL_MODE_FLAG=go-w,a+rX $BUILD_ACTION $EXTRA_SETTINGS || {echo "Build failed!"; exit 1}
+xcodebuild -buildstyle $FRAMEWORK_BUILDSTYLE INSTALL_MODE_FLAG=go-w,a+rX $BUILD_ACTION $EXTRA_SETTINGS || {echo "Build failed!"; exit 1}
 
 cd ${SnoizeFrameworkSource}/SnoizeMIDISpy
-pbxbuild -buildstyle $FRAMEWORK_BUILDSTYLE INSTALL_MODE_FLAG=go-w,a+rX $BUILD_ACTION $EXTRA_SETTINGS || {echo "Build failed!"; exit 1}
+xcodebuild -buildstyle $FRAMEWORK_BUILDSTYLE INSTALL_MODE_FLAG=go-w,a+rX $BUILD_ACTION $EXTRA_SETTINGS || {echo "Build failed!"; exit 1}
 
 cd ${SnoizeFrameworkSource}/DisclosableView
-pbxbuild -buildstyle $FRAMEWORK_BUILDSTYLE INSTALL_MODE_FLAG=go-w,a+rX $BUILD_ACTION $EXTRA_SETTINGS || {echo "Build failed!"; exit 1}
+xcodebuild -buildstyle $FRAMEWORK_BUILDSTYLE INSTALL_MODE_FLAG=go-w,a+rX $BUILD_ACTION $EXTRA_SETTINGS || {echo "Build failed!"; exit 1}
 
 cd ${SnoizeAppSource}/MIDIMonitor
-pbxbuild -buildstyle $APP_BUILDSTYLE DSTROOT=/ INSTALL_MODE_FLAG=go-w,a+rX $BUILD_ACTION $EXTRA_SETTINGS || {echo "Build failed!"; exit 1}
+xcodebuild -buildstyle $APP_BUILDSTYLE DSTROOT=/ INSTALL_MODE_FLAG=go-w,a+rX $BUILD_ACTION $EXTRA_SETTINGS || {echo "Build failed!"; exit 1}
 	# NOTE: We are relying on the app's project having an INSTALL_PATH
 	# set to $INSTALL_DIRECTORY. For some reason, if it is set to nothing in the project,
 	# setting it here will not cause the install to happen.
